apiVersion: v1
kind: Pod
metadata:
  name: currency-{{ .Values.pod.name }}-app
  labels:
    app: {{ .Values.pod.name }}-microservice
spec:
  containers:
  - name: currency-{{ .Values.pod.name }}
    image: hashicorp/http-echo:0.2.3
    args:
      - "-text=feature available in {{ .Values.pod.name }}"
      - -listen=:{{ .Values.pod.container.port}} 